Fix accounts panel width (#797)
dino/dino pull request #1017
Opened 2021-03-09 08:20 UTC by sshikaree

2021-03-23 11:45 UTC, fiaxh requested changes
Thanks for the PR.
I think it would be suitable to put those changes directly into the [`LabelHybrid`](https://github.com/dino/dino/blob/9cc3382abe801f0be96b79dcfc9cd4ac0272befa/main/src/ui/util/label_hybrid.vala#L11) (the parent of `EntryLabelHybrid`). That way, we fix the "widget gets to large and messes up window dimensions" issue for all usages of the `LabelHybrid`.

2021-03-24 13:29 UTC, sshikaree commented
Maybe it would be more consistent to add this changes [here](https://github.com/dino/dino/blob/9cc3382abe801f0be96b79dcfc9cd4ac0272befa/main/src/ui/util/label_hybrid.vala#L8) in properties list?

2021-03-24 14:33 UTC, fiaxh commented
@sshikaree Sounds good :+1:

2021-03-24 16:30 UTC, fiaxh approved these changes

2021-03-24 16:45 UTC, merged