Show file upload/download progress
dino/dino pull request #1491
Opened 2023-10-06 23:10 UTC by XaviDCR92

Fixes upstream issue #1350.

## Notes

Image uploads were incorrectly handled by Dino, as they were always reported as completed even if they were not, maybe so as to show the image preview from the start. Now, Dino shows the upload progress for all file types, and the image is only shown when completed.

2023-10-07 11:24 UTC, fiaxh requested changes
Thanks for your PR!

I added some review comments.

2023-10-16 19:29 UTC, XaviDCR92 commented
@fiaxh all issues have been already addressed. Could you please review again?

2023-12-10 15:19 UTC, fiaxh commented
In order to keep the discussions around this PR in one place:

There was an exchange on this topic in the Dino Channel a while back. mar-v-in suggested that it would be better to 

>do [the counting of transferred bytes] in file manager such that it applies to both [file transfer types] just like you did for receiving files

2025-01-12 18:52 UTC, fiaxh commented
Done in d78ec05.

2025-01-12 18:52 UTC, closed without merging